# Generated by Django 4.1.7 on 2023-03-28 06:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned', models.IntegerField(default=0)),
                ('not_started', models.IntegerField(default=0)),
                ('started', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('missing_merge_tags', models.IntegerField(default=0)),
                ('invalid_emails', models.IntegerField(default=0)),
                ('unsubscribed', models.IntegerField(default=0)),
                ('do_not_contact', models.IntegerField(default=0)),
                ('opened', models.IntegerField(default=0)),
                ('replied', models.IntegerField(default=0)),
                ('clicked', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('spam_test', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_daily_limit', models.IntegerField(default=0)),
                ('email_daily_limit', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Converted', 'Converted'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Not now', 'Not Now'), ('Auto reply', 'Auto Reply'), ('Delivery failed', 'Delivery Failed'), ('Do not contact', 'Do Not Contact'), ('Not categorized', 'Not Categorized'), ('Out of office', 'Out Of Office')], default='Not categorized', max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_replied_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('email_opens', models.IntegerField(default=0)),
                ('email_link_clicks', models.IntegerField(default=0)),
                ('active_campaigns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartreachapi.campaign')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
