# Generated by Django 4.1.7 on 2023-03-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartreachapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospects',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='prospects',
            name='active_campaigns',
        ),
        migrations.RemoveField(
            model_name='prospects',
            name='last_opened_at',
        ),
        migrations.RemoveField(
            model_name='prospects',
            name='last_replied_at',
        ),
        migrations.RemoveField(
            model_name='prospects',
            name='source',
        ),
        migrations.RemoveField(
            model_name='prospects',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
