# Generated by Django 4.1.7 on 2023-03-28 08:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreachapi', '0002_remove_prospects_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospects',
            name='email_link_clicks',
        ),
        migrations.RemoveField(
            model_name='prospects',
            name='email_opens',
        ),
        migrations.AlterField(
            model_name='prospects',
            name='list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
