# Generated by Django 4.1.7 on 2023-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreachapi', '0003_remove_prospects_email_link_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospects',
            name='owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
