# Generated by Django 4.1.7 on 2023-03-28 08:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreachapi', '0004_alter_prospects_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospects',
            name='list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
