# Generated by Django 4.1.7 on 2023-03-28 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreachapi', '0005_alter_prospects_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 28, 15, 3, 53, 384659)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospects',
            name='current_step_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospects',
            name='latest_reply_sentiment_uuid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospects',
            name='latest_task_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospects',
            name='prospect_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospects',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
