# Generated by Django 4.1.7 on 2023-04-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartreachapi', '0007_alter_prospects_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospects',
            unique_together=set(),
        ),
    ]
